{{- if .Values.apiTokenError.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "api-token-error.name" . }}
  labels:
    {{- include "api-token-error.labels" . | nindent 4 }}
spec:
  {{- if not .Values.apiTokenError.autoscaling.enabled }}
  replicas: {{ .Values.apiTokenError.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "api-token-error.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
      {{- with .Values.apiTokenError.podAnnotations }}
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "api-token-error.selectorLabels" . | nindent 8 }}
    spec:
      securityContext:
        {{- toYaml .Values.apiTokenError.podSecurityContext | nindent 8 }}
      imagePullSecrets:
        {{- include "common.imagePullSecrets" (dict "global" .Values.global "imagePullSecrets" .Values.apiTokenError.imagePullSecrets) | nindent 4 }}
      containers:
        - name: "{{ include "api-token-error.name" . }}"
          securityContext:
            {{- toYaml .Values.apiTokenError.securityContext | nindent 12 }}
{{- if .Values.apiTokenError.image.fullName }}
          image: "{{ .Values.apiTokenError.image.fullName }}"
{{- else }}
          image: "{{ .Values.apiTokenError.image.registry }}/{{ .Values.apiTokenError.image.name }}:{{ .Values.apiTokenError.image.tag }}"
{{- end }}
          imagePullPolicy: {{ .Values.apiTokenError.image.pullPolicy }}
          command: ["./api-token-error"]
          args: []
          env: []
          ports:
            - name: http
              containerPort: 8080
              protocol: TCP
            - name: grpc
              containerPort: 50001
              protocol: TCP
          resources:
            {{- if .Values.apiTokenError.merge.resources }}
              {{- toYaml .Values.apiTokenError.merge.resources | nindent 12 }}
            {{- else }}
              {{- toYaml .Values.apiTokenError.resources | nindent 12 }}
            {{- end }}
      {{- with .Values.apiTokenError.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiTokenError.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.apiTokenError.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
{{- end }}
