{{- $gomemlimit := include "catalyst.GetGoLangGOMEMLIMITFromResourceLimits" (dict "limits" .Values.management.resources.limits "golimit" .Values.management.goSoftLimit) }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "management.name" . }}
  labels:
    {{- include "merge.maps" (dict "base" (fromYaml (include "management.labels" .)) "overrides" .Values.management.merge.labels) | nindent 4 }}
spec:
  replicas: {{ .Values.management.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      {{- include "management.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/management-config: {{ include (print $.Template.BasePath "/management/configmap.yaml") . | sha256sum }}
        {{- with .Values.management.podAnnotations }}
        {{- toYaml . | nindent 8 }}
        {{- end }}
        dapr.io/app-id: management
        dapr.io/config: management
      labels:
        {{- include "merge.maps" (dict "base" (include "management.selectorLabels" . | fromYaml) "overrides" .Values.management.merge.selectorLabels) | nindent 8 }}
    spec:
      restartPolicy: Always
      serviceAccountName: {{ include "management.serviceAccountName" . }}
      securityContext:
        {{- include "merge.maps" (dict "base" .Values.management.podSecurityContext "overrides" .Values.management.merge.podSecurityContext) | nindent 8 }}
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- include "merge.maps" (dict "base" .Values.management.securityContext "overrides" .Values.management.merge.securityContext) | nindent 12 }}
          image: "{{ .Values.management.image.registry }}/{{ .Values.management.image.name }}:{{ .Values.management.image.tag }}"
          imagePullPolicy: {{ .Values.management.image.pullPolicy }}
          command: ["./management"]
          args:
          - "--log-level={{ .Values.management.logLevel }}"
          {{- if eq .Values.global.secrets.provider "redis" }}
          - "--secretsprovider=redis"
          - "--secrets_redis.host={{ required ".Values.global.secrets.redis.host entry required when .Values.global.secrets.provider is set to redis" .Values.global.secrets.redis.host }}"
          - "--secrets_redis.username={{ .Values.global.secrets.redis.username }}"
          - "--secrets_redis.password={{ .Values.global.secrets.redis.password }}"
          {{- end }}
          {{- if eq .Values.global.secrets.provider "aws" }}
          - "--secretsprovider=aws.secretmanager"
          - "--secrets_aws_secretmanager.region={{ required ".Values.global.secrets.aws.region entry required when .Values.global.secrets.provider is set to aws" .Values.global.secrets.aws.region }}"
          - "--secrets_aws_secretmanager.access_key={{ .Values.global.secrets.aws.access_key }}"
          - "--secrets_aws_secretmanager.secret_access_key={{ .Values.global.secrets.aws.secret_access_key }}"
          {{- end }}
          {{- if eq .Values.global.secrets.provider "kubernetes" }}
          - "--secretsprovider=kubernetes"
          {{- end }}
          env:
          - name: CONFIG_FILE_DIR
            value: /etc/management
          - name: NAMESPACE
            valueFrom:
              fieldRef:
                fieldPath: metadata.namespace
          {{- if (and $gomemlimit (ne $gomemlimit "0")) }}
          - name: GOMEMLIMIT
            value: {{ $gomemlimit }}
          {{- end }}
          {{- if .Values.management.extraEnvs }}
          {{- toYaml .Values.management.extraEnvs | nindent 10 }}
          {{- end }}
          {{- include "inject.patch" (dict "patch" .Values.management.patch.env "indent" 10) }}
          ports:
          {{- include "inject.patch" (dict "patch" .Values.management.patch.ports "indent" 10) }}
          resources:
            {{- if .Values.management.merge.resources }}
              {{- toYaml .Values.management.merge.resources | nindent 12 }}
            {{- else }}
              {{- toYaml .Values.management.resources | nindent 12 }}
            {{- end }}
          volumeMounts:
          - name: management-config
            mountPath: /etc/management
          - name: sentry-identity-token
            mountPath: /var/run/secrets/dapr.io/sentrytoken
            readOnly: true
          - name: trust-bundle
            mountPath: /var/run/secrets/diagrid.io/trust
            readOnly: true
          {{- include "inject.patch" (dict "patch" .Values.management.patch.volumeMounts "indent" 10) }}
        {{- include "inject.patch" (dict "patch" .Values.management.patch.containers "indent" 6) }}
      volumes:
      - name: management-config
        configMap:
          name: {{ include "management.name" . }}-config
      - name: trust-bundle
        configMap:
          name: ca-certificates-bundle
      - name: sentry-identity-token
        projected:
          defaultMode: 420
          sources:
          - serviceAccountToken:
              audience: dapr.io/sentry
              expirationSeconds: 7200
              path: token
      {{- include "inject.patch" (dict "patch" .Values.management.patch.volumes "indent" 6) }}
      nodeSelector:
        {{- include "merge.maps" (dict "base" .Values.management.nodeSelector "overrides" .Values.management.merge.nodeSelector) | nindent 8 }}
      affinity:
        {{- include "merge.maps" (dict "base" .Values.management.affinity "overrides" .Values.management.merge.affinity) | nindent 8 }}
      tolerations:
        {{- if or .Values.management.tolerations .Values.management.merge.tolerations }}
        {{- if .Values.management.tolerations }}
        {{- toYaml .Values.management.tolerations | nindent 8 }}
        {{- end }}
        {{- if .Values.management.merge.tolerations }}
        {{- toYaml .Values.management.merge.tolerations | nindent 8 }}
        {{- end }}
        {{- else }}
        []
        {{- end }}
