apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "management.serviceAccountName" . }}
  labels:
    {{- include "management.labels" . | nindent 4 }}
  {{- with .Values.management.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
