apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "agent.serviceAccountName" . }}
  labels:
    {{- include "agent.labels" . | nindent 4 }}
  annotations:
  {{- with .Values.global.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
  {{- with .Values.agent.serviceAccount.annotations }}
    {{- toYaml . | nindent 4 }}
  {{- end }}
