{{- $envoyImage := printf "%s/%s:%s" .Values.gateway.envoy.image.registry .Values.gateway.envoy.image.name .Values.gateway.envoy.image.tag }}
{{- $identityInjectorImage := printf "%s/%s:%s" .Values.gateway.identityInjector.image.registry .Values.gateway.identityInjector.image.name .Values.gateway.identityInjector.image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-gateway
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- with .Values.gateway.envoy.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "merge.maps" (dict "base" (fromYaml (include "gateway.envoy.labels" .)) "overrides" .Values.gateway.envoy.merge.labels) | nindent 4 }}
spec:
  replicas: {{ if .Values.gateway.ha.enabled }}{{ .Values.gateway.ha.minReplicas }}{{ else }}{{ .Values.gateway.envoy.replicaCount }}{{ end }}
  selector:
    matchLabels:
      {{- include "gateway.envoy.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      annotations:
        checksum/controlplane-config: {{ include (print $.Template.BasePath "/gateway/configmap.yaml") . | sha256sum }}
      labels:
        {{- include "merge.maps" (dict "base" (include "gateway.envoy.selectorLabels" . | fromYaml) "overrides" .Values.gateway.envoy.merge.selectorLabels) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gateway.envoy.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.envoy.podSecurityContext | nindent 8 }}
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - command:
            - ./identity-injector
          env:
            - name: IDENTITY_TRUST_DOMAIN
              value: prj-root.cra.diagrid.io
            - name: IDENTITY_APPID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IDENTITY_ROOT_DIR
              value: /var/run/secrets/diagrid.io
            - name: IDENTITY_CA_CERT
              value: /var/run/secrets/diagrid.io/trust/ca.crt
            - name: IDENTITY_TLS_DIR
              value: /var/run/secrets/diagrid.io/tls
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: {{ $identityInjectorImage }}
          imagePullPolicy: IfNotPresent
          name: identity-injector
          resources:
            {{- toYaml .Values.gateway.identityInjector.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/diagrid.io
              name: tls-certs
            - mountPath: /var/run/secrets/diagrid.io/trust/ca.crt
              name: trust-bundle
              readOnly: true
              subPath: ca.crt
            - mountPath: /var/run/secrets/dapr.io/sentrytoken
              name: dapr-identity-token
              readOnly: true
      {{- end }}
        - name: envoy
          securityContext:
            {{- toYaml .Values.gateway.envoy.securityContext | nindent 12 }}
          image: "{{ $envoyImage }}"
          args:
            - "-c"
            - "/etc/envoy/bootstrap-envoy.yaml"
            - "--service-node"
            - "catalyst-gateway"
            - "--service-cluster"
            - "catalyst-gateway"
          resources:
            {{- toYaml .Values.gateway.envoy.resources | nindent 12 }}
          ports:
            - name: http
              containerPort: {{ .Values.gateway.envoy.service.targetPort }}
              protocol: TCP
          volumeMounts:
            - name: envoy-config
              mountPath: /etc/envoy
              readOnly: true
            {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
            - mountPath: /var/run/secrets/diagrid.io
              name: tls-certs
            - mountPath: /var/run/secrets/diagrid.io/trust/ca.crt
              name: trust-bundle
              readOnly: true
              subPath: ca.crt
            - mountPath: /var/run/secrets/dapr.io/sentrytoken
              name: dapr-identity-token
              readOnly: true
            {{- end }}
      volumes:
        - name: envoy-config
          configMap:
            name: envoy-config
        {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - configMap:
            defaultMode: 420
            name: ca-certificates-bundle
          name: trust-bundle
        - name: tls-certs
          emptyDir: {}
        - name: dapr-identity-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: dapr.io/sentry
                  expirationSeconds: 7200
                  path: token
        {{- end }}
      nodeSelector:
        {{- toYaml .Values.gateway.envoy.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.gateway.envoy.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.gateway.envoy.tolerations | nindent 8 }}
---
{{- $controlplaneImage := printf "%s/%s:%s" .Values.gateway.controlplane.image.registry .Values.gateway.controlplane.image.name .Values.gateway.controlplane.image.tag }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: catalyst-gateway-controlplane
  annotations:
    {{- with .Values.gateway.controlplane.podAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  labels:
    {{- include "merge.maps" (dict "base" (fromYaml (include "gateway.controlplane.labels" .)) "overrides" .Values.gateway.controlplane.merge.labels) | nindent 4 }}
spec:
  replicas: {{ if .Values.gateway.ha.enabled }}{{ .Values.gateway.ha.minReplicas }}{{ else }}{{ .Values.gateway.controlplane.replicaCount }}{{ end }}
  selector:
    matchLabels:
      {{- include "gateway.controlplane.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "merge.maps" (dict "base" (include "gateway.controlplane.selectorLabels" . | fromYaml) "overrides" .Values.gateway.controlplane.merge.selectorLabels) | nindent 8 }}
    spec:
      serviceAccountName: {{ include "gateway.controlplane.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.gateway.controlplane.podSecurityContext | nindent 8 }}
      {{- with .Values.global.image.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      containers:
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - command:
          - ./identity-injector
          env:
            - name: IDENTITY_TRUST_DOMAIN
              value: prj-root.cra.diagrid.io
            - name: IDENTITY_APPID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: IDENTITY_ROOT_DIR
              value: /var/run/secrets/diagrid.io
            - name: IDENTITY_CA_CERT
              value: /var/run/secrets/diagrid.io/trust/ca.crt
            - name: IDENTITY_TLS_DIR
              value: /var/run/secrets/diagrid.io/tls
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
          image: {{ $identityInjectorImage }}
          imagePullPolicy: IfNotPresent
          name: identity-injector
          resources:
            {{- toYaml .Values.gateway.identityInjector.resources | nindent 12 }}
          terminationMessagePath: /dev/termination-log
          terminationMessagePolicy: File
          volumeMounts:
            - mountPath: /var/run/secrets/diagrid.io
              name: tls-certs
            - mountPath: /var/run/secrets/diagrid.io/trust/ca.crt
              name: trust-bundle
              readOnly: true
              subPath: ca.crt
            - mountPath: /var/run/secrets/dapr.io/sentrytoken
              name: dapr-identity-token
              readOnly: true
      {{- end }}
        - name: catalyst-gateway-controlplane
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: LEADER_ELECTION_ENABLED
              value: {{ .Values.gateway.ha.enabled | quote }}
          {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
            - name: XDS_SERVER_TLS_CERT
              value: "/var/run/secrets/diagrid.io/tls/tls.crt"
            - name: XDS_SERVER_TLS_KEY
              value: "/var/run/secrets/diagrid.io/tls/tls.key"
            - name: XDS_SERVER_CA_CERT
              value: "/var/run/secrets/diagrid.io/trust/ca.crt"
          {{- end }}
          securityContext:
            {{- toYaml .Values.gateway.controlplane.securityContext | nindent 12 }}
          image: "{{ $controlplaneImage }}"
          resources:
            {{- toYaml .Values.gateway.controlplane.resources | nindent 12 }}
          ports:
            - name: httphealthcheck
              containerPort: {{ .Values.gateway.controlplane.deployment.httpHealthCheck.containerPort }}
              protocol: TCP
            - name: http-xds
              containerPort: {{ .Values.gateway.controlplane.deployment.httpXDS.containerPort }}
              protocol: TCP
          volumeMounts:
          {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
            - mountPath: /var/run/secrets/diagrid.io
              name: tls-certs
            - mountPath: /var/run/secrets/diagrid.io/trust/ca.crt
              name: trust-bundle
              subPath: ca.crt
          {{- end }}
      volumes:
      {{- if .Values.gateway.controlplane.xds.mtls.enabled }}
        - configMap:
            defaultMode: 420
            name: ca-certificates-bundle
          name: trust-bundle
        - emptyDir: {}
          name: tls-certs
        - name: dapr-identity-token
          projected:
            defaultMode: 420
            sources:
              - serviceAccountToken:
                  audience: dapr.io/sentry
                  expirationSeconds: 7200
                  path: token
      {{- end }}
      nodeSelector:
        {{- toYaml .Values.gateway.controlplane.nodeSelector | nindent 8 }}
      affinity:
        {{- toYaml .Values.gateway.controlplane.affinity | nindent 8 }}
      tolerations:
        {{- toYaml .Values.gateway.controlplane.tolerations | nindent 8 }}