{{- $isNodePort := eq .Values.gateway.envoy.service.type "NodePort" }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.envoy.service.name }}
  annotations:
{{- with .Values.gateway.envoy.podAnnotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "gateway.envoy.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway.envoy.selectorLabels" . | nindent 6 }}
  ports:
    - name: http
      port: {{ .Values.gateway.envoy.service.port }}
      targetPort: {{ .Values.gateway.envoy.service.targetPort }}
      {{- if $isNodePort }}
      nodePort: {{ .Values.gateway.envoy.service.port }}
      {{- end }}
      protocol: TCP
    {{- if .Values.gateway.tls.enabled }}
    - name: https
      port: {{ .Values.gateway.envoy.service.httpsPort }}
      targetPort: {{ .Values.gateway.envoy.service.httpsTargetPort }}
      {{- if $isNodePort }}
      nodePort: {{ .Values.gateway.envoy.service.httpsPort }}
      {{- end }}
      protocol: TCP
    {{- end }}
  type: {{ .Values.gateway.envoy.service.type }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.gateway.controlplane.service.name }}
  annotations:
{{- with .Values.gateway.controlplane.podAnnotations }}
{{ toYaml . | nindent 4 }}
{{- end }}
  labels:
    {{- include "gateway.controlplane.labels" . | nindent 4 }}
spec:
  selector:
    {{- include "gateway.controlplane.selectorLabels" . | nindent 6 }}
  ports:
    - name: http-healthz
      port: {{ .Values.gateway.controlplane.service.httpHealthCheck.port }}
      targetPort: {{ .Values.gateway.controlplane.service.httpHealthCheck.targetPort }}
      protocol: TCP
    - name: http-xds
      port: {{ .Values.gateway.controlplane.service.httpXDS.port }}
      targetPort: {{ .Values.gateway.controlplane.service.httpXDS.targetPort }}
      protocol: TCP
  type: {{ .Values.gateway.controlplane.service.type }}
  clusterIP: {{ .Values.gateway.controlplane.service.clusterIP }}
