apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway.envoy.serviceAccountName" . }}
  labels:
    {{- include "gateway.envoy.labels" . | nindent 4 }}
  {{- with .Values.gateway.envoy.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "gateway.controlplane.serviceAccountName" . }}
  labels:
    {{- include "gateway.controlplane.labels" . | nindent 4 }}
  {{- with .Values.gateway.controlplane.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
