{{- if and (not .Values.gateway.tls.existingSecret) (or .Values.gateway.tls.cert .Values.gateway.tls.key) }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "gateway.tlsSecretName" . }}
  annotations:
    checksum/tls-cert: {{ .Values.gateway.tls.cert | sha256sum }}
    checksum/tls-key: {{ .Values.gateway.tls.key | sha256sum }}
type: kubernetes.io/tls
data:
  tls.crt: {{ .Values.gateway.tls.cert | b64enc | quote }}
  tls.key: {{ .Values.gateway.tls.key | b64enc | quote }}
{{- end }}
