apiVersion: v2
name: catalyst
icon: https://storage.googleapis.com/bkt-n-assets-common-us-central1/Diagrid_Logos/Diagrid.png
description: Helm chart for Catalyst
type: application
version: '0.1.0'
appVersion: '0.0.1'
dependencies:
  - name: metrics-server
    version: 3.10.0
    repository: "https://kubernetes-sigs.github.io/metrics-server"
    condition: metricsServer.enabled
