apiVersion: v2
name: catalyst
icon: https://storage.googleapis.com/bkt-n-assets-common-us-central1/Diagrid_Logos/Diagrid.png
description: Helm chart for Diagrid Catalyst
type: application
version: '0.7.0'
appVersion: '0.0.1'
