global:
  control_plane_url: cra-cloudgrid.dev.d.diagrid.io:443
  sentry:
    remote_endpoint: sentry.dev.d.diagrid.io:443
    diagrid_trust_anchors_endpoint: https://trust-pem.dev.d.diagrid.io
  nats:
    endpoint: tls://client.events.dev.d.diagrid.io:443

agent:
  config:
    control_plane_http_url: https://api.dev.diagrid.io
    otel:
      metrics_endpoint: https://cra-metrics.dev.d.diagrid.io/api/v1/push
      loki_endpoint: https://cra-logs.dev.d.diagrid.io/loki/api/v1/push

management:
  config:
    http_server_auth:
      domain: "api.dev.diagrid.io"