global:
  control_plane_url: cra.local.diagrid.io:443
  sentry:
    remote_endpoint: sentry.local.diagrid.io:443
    diagrid_trust_anchors_endpoint: https://trust-pem.local.diagrid.io
    diagrid_trust_anchors_endpoint_insecure: true
  nats:
    endpoint: tls://client.events.local.diagrid.io:443

agent:
  config:
    control_plane_http_url: https://api.local.diagrid.io
    control_plane_http_insecure: true
    otel:
      metrics_endpoint: https://cra-metrics.local.diagrid.io/api/v1/push
      loki_endpoint: https://cra-logs.local.diagrid.io/loki/api/v1/push

management:
  config:
    http_server_auth:
      domain: "api.local.diagrid.io"
