agent:
  config:
    control_plane_url: cra.local.diagrid.io:443
    control_plane_http_url: https://api.local.diagrid.io
    control_plane_http_insecure: true
    nats:
      endpoint: tls://client.events.local.diagrid.io:443
    sentry:
      remote_endpoint: sentry.local.diagrid.io:443
      diagrid_trust_anchors_endpoint: https://trust-pem.local.diagrid.io
      diagrid_trust_anchors_endpoint_insecure: true
    # TODO add cortex and loki endpoints
management:
  config:
    nats:
      endpoint: tls://client.events.local.diagrid.io:443
    sentry:
      remote_endpoint: sentry.local.diagrid.io:443
      diagrid_trust_anchors_endpoint: https://trust-pem.local.diagrid.io
      diagrid_trust_anchors_endpoint_insecure: true
