name: Lint & Validate Helm Charts

on:
  pull_request:
    branches:
      - main  

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.3'

      - name: Helm Lint
        run: |
          helm lint ./charts

      - name: Helm Template
        run: |
          helm template my-release ./charts > rendered.yaml

      - name: Set up Kind
        uses: helm/kind-action@v1
        with:
          kubectl_version: '1.28.4' 

      - name: Helm Install
        run: |
          helm install my-release ./charts --namespace test --create-namespace
