name: Lint & Validate Helm Charts

on:
  pull_request:
    branches:
      - main  

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.3'

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Kind
        uses: helm/kind-action@v1.3.0

      - name: Install Contour CRDs
        run: |
          kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
          kubectl wait --for=condition=Established --timeout=60s crd/httpproxies.projectcontour.io

      - name: Helm Lint
        run: |
          helm lint ./

      - name: Helm Template
        run: |
          helm template my-release ./ --namespace test --debug > rendered.yaml

      - name: Helm Install
        run: |
          helm upgrade --install my-release ./ --namespace test --create-namespace --wait --timeout 15m
