name: Catalyst Helm Chart CI

on:
  pull_request:
    branches:
      - main

jobs:
  lint-and-validate:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up Helm
        uses: azure/setup-helm@v4
        with:
          version: 'v3.14.3'

      - name: Install kubectl
        uses: azure/setup-kubectl@v4

      - name: Set up Kind
        uses: helm/kind-action@v1.3.0
        with:
          cluster_name: 'helm-test-cluster'

      - name: Set Kubeconfig for Kind
        run: |
          kind get kubeconfig --name helm-test-cluster > $HOME/.kube/config

      - name: Verify Cluster Nodes are Ready
        run: |
          kubectl get nodes
          kubectl wait --for=condition=Ready nodes --all --timeout=60s

      - name: Install Contour CRDs
        run: |
          kubectl apply -f https://projectcontour.io/quickstart/contour.yaml
          kubectl wait --for=condition=Established --timeout=60s crd/httpproxies.projectcontour.io

      - name: Annotate Contour CRDs
        run: |
          for crd in contourdeployments.projectcontour.io \
                     contourconfigurations.projectcontour.io \
                     httpproxies.projectcontour.io \
                     tlscertificatedelegations.projectcontour.io \
                     extensionservices.projectcontour.io; do
            kubectl annotate crd $crd \
              meta.helm.sh/release-name=my-release \
              meta.helm.sh/release-namespace=test --overwrite
            kubectl label crd $crd \
              app.kubernetes.io/managed-by=Helm --overwrite
          done

      - name: Helm Lint
        working-directory: charts/catalyst
        run: make helm-lint

      - name: Helm Template
        working-directory: charts/catalyst
        run: |-
          make helm-template

      # set to dry-run temporarily
      - name: Helm Upgrade or Install with Retries
        working-directory: charts/catalyst
        run: make helm-upgrade